apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: back-end
  name: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: back-end
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/book-api-project-node-network: "true"
        io.kompose.service: back-end
    spec:
      containers:
        - args:
            - npm
            - run
            - start
          image: back-end
          name: back-end
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /usr/src/app
              name: back-end-claim0
            - mountPath: /usr/src/app/node_modules
              name: back-end-claim1
          workingDir: /usr/src/app
      restartPolicy: Always
      volumes:
        - name: back-end-claim0
          persistentVolumeClaim:
            claimName: back-end-claim0
        - name: back-end-claim1
          persistentVolumeClaim:
            claimName: back-end-claim1
