apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: back-end
  name: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: back-end
      app: myApp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/book-api-project-node-network: "true"
        io.kompose.service: back-end
        app: myApp
    spec:
      containers:
        - command: ['npm run start']
          image: bookapiproject.azurecr.io/k8sdemo
          name: back-end
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /usr/src/app
              name: back-end-claim0
            - mountPath: /usr/src/app/node_modules
              name: back-end-claim1
          workingDir: /usr/src/app
      restartPolicy: Always
      volumes:
        - name: back-end-claim0
          persistentVolumeClaim:
            claimName: back-end-claim0
        - name: back-end-claim1
          persistentVolumeClaim:
            claimName: back-end-claim1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
      app: myApp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/book-api-project-node-network: "true"
        io.kompose.service: db
        app: myApp
    spec:
      containers:
        - env:
            - name: POSTGRES_DATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: prateeknarayanan
          image: bookapiproject.azurecr.io/k8sdemo
          name: db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-claim0
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: db-claim0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: front-end
    app: myApp
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front-end
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/book-api-project-node-network: "true"
        io.kompose.service: front-end
        app: myApp
    spec:
      containers:
        - command: ['npm run start']
          image: bookapiproject.azurecr.io/k8sdemo
          name: front-end
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /usr/src/app
              name: front-end-claim0
            - mountPath: /usr/src/app/node_modules
              name: front-end-claim1
          workingDir: /usr/src/app
      restartPolicy: Always
      volumes:
        - name: front-end-claim0
          persistentVolumeClaim:
            claimName: front-end-claim0
        - name: front-end-claim1
          persistentVolumeClaim:
            claimName: front-end-claim1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
      app: myApp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/book-api-project-node-network: "true"
        io.kompose.service: nginx
        app: myApp
    spec:
      containers:
        - image: bookapiproject.azurecr.io/k8sdemo
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 8000
              protocol: TCP
          tty: true
      restartPolicy: Always
