name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@master

         - uses: Azure/docker-login@v1
           with:
              login-server: bookapiproject.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

         - run: |
              docker-compose up --build -d
              docker-compose push

         - uses: azure/setup-kubectl@v2.0

         # Set the target AKS cluster.
         - uses: Azure/aks-set-context@v1
           with:
              creds: '${{ secrets.AZURE_CREDENTIALS }}'
              cluster-name: bookapiproject
              resource-group: cloud-shell-storage-westus

         - uses: Azure/k8s-create-secret@v1.1
           with:
              container-registry-url: bookapiproject.azurecr.io
              container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
              container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
              secret-name: demo-k8s-secret

         - uses: Azure/k8s-deploy@v4
           with:
              action: deploy
              manifests: |
               manifests/deployment.yml
               manifests/service.yml
              images: |
                 bookapiproject.azurecr.io/k8sdemo:latest
              imagepullsecrets: |
                 demo-k8s-secret