name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@master

         - uses: Azure/docker-login@v1
           with:
              login-server: bookapiproject.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

         - run: |
              docker build . -t bookapiproject.azurecr.io/k8sdemo:${{ github.sha }}
              docker push bookapiproject.azurecr.io/k8sdemo:${{ github.sha }}

         - uses: azure/setup-kubectl@v2.0

         # Set the target AKS cluster.
         - uses: Azure/aks-set-context@v1
           with:
              creds: '${{ secrets.AZURE_CREDENTIALS }}'
              cluster-name: bookapiproject
              resource-group: cloud-shell-storage-westus

         - uses: Azure/k8s-create-secret@v1.1
           with:
              container-registry-url: bookapiproject.azurecr.io
              container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
              container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
              secret-name: demo-k8s-secret

         - uses: Azure/k8s-deploy@v4
           with:
              action: deploy
              manifests: |
                 back-end-deployment.yaml
                 db-deployment.yaml
                 front-end-deployment.yaml
                 nginx-deployment.yaml
                 back-end-service.yaml
                 db-service.yaml
                 front-end-service.yaml
                 nginx-service.yaml
                 back-end-claim0-persistentvolumeclaim.yaml
                 back-end-claim1-persistentvolumeclaim.yaml
                 db-claim0-persistentvolumeclaim.yaml
                 front-end-claim0-persistentvolumeclaim.yaml
                 front-end-claim1-persistentvolumeclaim.yaml
              images: |
                 demo.azurecr.io/k8sdemo:${{ github.sha }}
              imagepullsecrets: |
                 demo-k8s-secret